export const USERNAMES = [
  "DaringTrader42",
  "FrugalMaven",
  "LuckyInvestor888",
  "SteadyAnalyst",
  "WiseGuru",
  "DiamondHandsPro",
  "PaperHandedPanicSeller",
  "RocketMoonboy",
  "ApeHodler7",
  "BullishStonkMachine",
  "BearishChartMaster",
  "ZenInvestor",
  "FOMOChamp",
  "REKTLegend",
  "LamboVisionary",
  "WhaleWizard",
  "DegenHustler",
  "SharpStrategist",
  "ThriftyPioneer",
  "VigilantSavant",
  "Bitcoin Baron",
  "Ethereum Emperor",
  "Altcoin Alchemist",
  "DeFi Dynamo",
  "NFT Navigator",
  "Token Titan",
  "Bear Market Brawler",
  "Bull Run Billionaire",
  "Dip Buyer Deluxe",
  "Green Candle Guru",
  "Red Candle Renegade",
  "HODL Hero",
  "Swing Trade Sultan",
  "Day Trade Deity",
  "Long Term Legend",
  "Short Squeeze Specialist",
  "Meme Stock Monarch",
  "Dollar Cost Averaging Ace",
  "Financial Freedom Fighter",
  "Portfolio Prince",
];

export const getRandomUsername = () => {
  const randomIndex = Math.floor(Math.random() * USERNAMES.length);
  return USERNAMES[randomIndex];
};
